{"name": "test_login_invalid_username", "status": "passed", "start": 1754560176230, "stop": 1754560176245, "uuid": "23bd6dda-0836-4cc7-80d8-56e70127318e", "historyId": "f51fd9365223daafc6506ba7162a9e9d", "testCaseId": "f51fd9365223daafc6506ba7162a9e9d", "fullName": "secure-auth-api.tests.test_auth.TestUserLogin#test_login_invalid_username", "labels": [{"name": "parentSuite", "value": "secure-auth-api.tests"}, {"name": "suite", "value": "test_auth"}, {"name": "subSuite", "value": "TestUserLogin"}, {"name": "host", "value": "DESKTOP-32KVTAU"}, {"name": "thread", "value": "19728-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "secure-auth-api.tests.test_auth"}], "titlePath": ["secure-auth-api", "tests", "test_auth.py", "TestUserLogin"]}